using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Helmion.Desktop.Core;

/// <summary>
/// Raised when a pasted Claude subscription token cannot be accepted. The message is written to
/// be shown to the user verbatim.
/// </summary>
public sealed class ClaudeSubscriptionAuthException(string message) : Exception(message);

/// <summary>
/// A Claude subscription token generated by <c>claude setup-token</c>.
///
/// <para>
/// UNLIKE Grok, OpenAI and Google, this is NOT a browser OAuth flow Helmion drives itself.
/// Anthropic restricts subscription OAuth to Claude Code and claude.ai only — using a raw
/// `/login` session credential from another app is a Consumer Terms of Service violation with
/// server-side enforcement since January 2026 (confirmed against Anthropic's own Legal &amp;
/// Compliance page and reproduced against a live token: outside-app requests come back
/// "This credential is only authorized for use with Claude Code and cannot be used for other
/// API requests"). <c>claude setup-token</c> is the mechanism Anthropic built on purpose for
/// exactly this situation — a long-lived (one year), subscription-backed token meant to leave
/// the terminal, confirmed 2026-08-04 straight from Anthropic's own docs
/// (code.claude.com/docs/en/authentication, "Generate a long-lived token" section).
/// </para>
///
/// <para>
/// So Helmion's side of this is: the user runs <c>claude setup-token</c> themselves (requires
/// the Claude Code CLI, which mints the token against their own Pro/Max/Team/Enterprise plan),
/// copies what prints to their terminal, and pastes it here. There is no refresh token — the
/// docs describe the command printing a token and nothing else; when this one expires the user
/// runs the command again and pastes the new one.
/// </para>
/// </summary>
public sealed record ClaudeSubscriptionToken(
    string AccessToken,
    DateTimeOffset? ExpiresAt,
    string? Email)
{
    /// <summary>
    /// True only when the token's own exp claim says it has lapsed. A token whose expiry can't
    /// be read is treated as not-yet-expired — Anthropic's own 401 on the next request is the
    /// authoritative signal, not a guess made here.
    /// </summary>
    public bool IsExpired(DateTimeOffset now) => ExpiresAt is { } at && at <= now;
}

/// <summary>How the next Claude request will authenticate.</summary>
public enum ClaudeAuthMode
{
    None,
    Subscription,
    ApiKey,
}

public sealed record ClaudeCredential(ClaudeAuthMode Mode, string? Token, string StatusLabel)
{
    public bool CanSend => Mode != ClaudeAuthMode.None && !string.IsNullOrWhiteSpace(Token);
}

/// <summary>
/// On-disk home for a pasted Claude subscription token, DPAPI-encrypted at
/// <see cref="DataProtectionScope.CurrentUser"/> scope — same rationale and mechanism as
/// <see cref="SuperGrokTokenStore"/>: this is a bearer credential for the whole account and must
/// never land in the plaintext .env that child agent processes inherit.
/// </summary>
public sealed class ClaudeSubscriptionTokenStore
{
    private readonly string _path;

    public ClaudeSubscriptionTokenStore(string? path = null)
    {
        _path = path ?? DefaultPath();
    }

    public static string DefaultPath() => System.IO.Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Helmion",
        "claude-subscription-token.dat");

    public string FilePath => _path;

    public bool Exists => File.Exists(_path);

    public ClaudeSubscriptionToken? Load()
    {
        if (!File.Exists(_path)) return null;

        try
        {
            var plaintext = ProtectedData.Unprotect(
                File.ReadAllBytes(_path),
                Entropy,
                DataProtectionScope.CurrentUser);
            var record = JsonSerializer.Deserialize<StoredToken>(plaintext);
            if (record?.AccessToken is null or "") return null;

            return new ClaudeSubscriptionToken(
                record.AccessToken,
                record.ExpiresAtUnix is { } unix ? DateTimeOffset.FromUnixTimeSeconds(unix) : null,
                record.Email);
        }
        catch (Exception ex) when (ex is CryptographicException or JsonException or IOException
                                       or UnauthorizedAccessException)
        {
            return null;
        }
    }

    public void Save(ClaudeSubscriptionToken token)
    {
        ArgumentNullException.ThrowIfNull(token);

        var payload = JsonSerializer.SerializeToUtf8Bytes(new StoredToken
        {
            AccessToken = token.AccessToken,
            ExpiresAtUnix = token.ExpiresAt?.ToUnixTimeSeconds(),
            Email = token.Email,
        });

        var directory = System.IO.Path.GetDirectoryName(_path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllBytes(
            _path,
            ProtectedData.Protect(payload, Entropy, DataProtectionScope.CurrentUser));
    }

    public void Clear()
    {
        try
        {
            if (File.Exists(_path)) File.Delete(_path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Sign-out is best effort; the caller already dropped the in-memory copy.
        }
    }

    private static readonly byte[] Entropy =
        Encoding.UTF8.GetBytes("Helmion.ClaudeSubscription.SetupToken.v1");

    private sealed class StoredToken
    {
        [JsonPropertyName("access_token")] public string? AccessToken { get; set; }
        [JsonPropertyName("expires_at")] public long? ExpiresAtUnix { get; set; }
        [JsonPropertyName("email")] public string? Email { get; set; }
    }
}

/// <summary>
/// Validates a pasted token's shape, reads what claims it can for display, and resolves the
/// credential for a request — API key wins only when there is no stored subscription token,
/// mirroring the "subscription first, key as fallback" order used for Grok.
/// </summary>
public sealed class ClaudeSubscriptionCredentialProvider
{
    private readonly ClaudeSubscriptionTokenStore _store;
    private ClaudeSubscriptionToken? _token;

    public ClaudeSubscriptionCredentialProvider(ClaudeSubscriptionTokenStore? store = null)
    {
        _store = store ?? new ClaudeSubscriptionTokenStore();
        _token = _store.Load();
    }

    public bool IsSignedIn => _token is not null;
    public string? SignedInEmail => _token?.Email;
    public DateTimeOffset? TokenExpiresAt => _token?.ExpiresAt;

    /// <summary>
    /// Accepts a pasted <c>claude setup-token</c> value. Does the minimum sanity check possible
    /// without calling Anthropic.
    ///
    /// <para>
    /// CORRECTED 2026-08-04: the original check assumed a dot-separated JWT shape. A real token
    /// pasted by Troy proved that wrong — it is an opaque bearer string prefixed
    /// <c>sk-ant-oat01-</c> (Anthropic's own OAuth-access-token prefix, distinct from
    /// <c>sk-ant-api03-</c> for a normal API key), with no dots at all. The old check would have
    /// rejected every real token this method is meant to accept. Now checks the real prefix
    /// instead of an assumed shape.
    /// </para>
    /// </summary>
    public void SaveToken(string pastedToken)
    {
        var trimmed = pastedToken?.Trim() ?? "";
        if (trimmed.Length == 0)
        {
            throw new ClaudeSubscriptionAuthException("Paste the token printed by \"claude setup-token\" first.");
        }
        if (!trimmed.StartsWith("sk-ant-oat", StringComparison.Ordinal) || trimmed.Length < 40)
        {
            throw new ClaudeSubscriptionAuthException(
                "That doesn't look like a token from \"claude setup-token\" (expected it to start "
                + "with sk-ant-oat...) — check you copied the whole line and try again.");
        }

        var (email, expiry) = ClaudeSubscriptionTokenReader.ReadClaims(trimmed);
        var token = new ClaudeSubscriptionToken(trimmed, expiry, email);
        _token = token;
        _store.Save(token);
    }

    public void SignOut()
    {
        _token = null;
        _store.Clear();
    }

    public ClaudeCredential Resolve(string? apiKey)
    {
        var hasApiKey = !string.IsNullOrWhiteSpace(apiKey);

        if (_token is null)
        {
            return hasApiKey
                ? new ClaudeCredential(ClaudeAuthMode.ApiKey, apiKey, ApiKeyLabel)
                : new ClaudeCredential(
                    ClaudeAuthMode.None,
                    null,
                    "Not signed in — paste a token from \"claude setup-token\", or an Anthropic API key.");
        }

        if (_token.IsExpired(DateTimeOffset.UtcNow))
        {
            return hasApiKey
                ? new ClaudeCredential(
                    ClaudeAuthMode.ApiKey,
                    apiKey,
                    $"{ApiKeyLabel} — the pasted Claude subscription token expired. Run "
                    + "\"claude setup-token\" again and paste the new one.")
                : new ClaudeCredential(
                    ClaudeAuthMode.None,
                    null,
                    "The pasted Claude subscription token expired. Run \"claude setup-token\" "
                    + "again and paste the new one. There is no API key to fall back to.");
        }

        var who = string.IsNullOrWhiteSpace(_token.Email) ? "" : $" ({_token.Email})";
        return new ClaudeCredential(
            ClaudeAuthMode.Subscription,
            _token.AccessToken,
            $"Using Claude subscription{who}");
    }

    private const string ApiKeyLabel = "Using API key";
}

/// <summary>
/// Reads the unsigned <c>email</c> and <c>exp</c> claims out of a setup-token so the UI can say
/// who is signed in and when to expect it to lapse. Deliberately not a validating JWT parse,
/// mirroring <see cref="SuperGrokTokenReader"/> — Helmion asserts nothing about the signature.
/// </summary>
public static class ClaudeSubscriptionTokenReader
{
    public static (string? Email, DateTimeOffset? Expiry) ReadClaims(string? token)
    {
        var payload = ReadPayload(token);
        if (payload is null) return (null, null);

        var email = payload.Value.TryGetProperty("email", out var emailEl)
            && emailEl.ValueKind == JsonValueKind.String
                ? emailEl.GetString()
                : null;

        var expiry = payload.Value.TryGetProperty("exp", out var expEl) && expEl.TryGetInt64(out var seconds)
            ? DateTimeOffset.FromUnixTimeSeconds(seconds)
            : (DateTimeOffset?)null;

        return (email, expiry);
    }

    private static JsonElement? ReadPayload(string? token)
    {
        if (string.IsNullOrWhiteSpace(token)) return null;

        var parts = token.Split('.');
        if (parts.Length < 2) return null;

        try
        {
            var segment = parts[1].Replace('-', '+').Replace('_', '/');
            segment = (segment.Length % 4) switch
            {
                2 => segment + "==",
                3 => segment + "=",
                0 => segment,
                _ => null!,
            };
            if (segment is null) return null;

            using var document = JsonDocument.Parse(Convert.FromBase64String(segment));
            return document.RootElement.Clone();
        }
        catch (Exception ex) when (ex is FormatException or JsonException)
        {
            return null;
        }
    }
}
