import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const page = await readFile(new URL('../web/cloud-admin/index.html', import.meta.url), 'utf8');
const script = await readFile(new URL('../web/cloud-admin/app.js', import.meta.url), 'utf8');
const liveAdmin = await readFile(new URL('../src/cloud/live-admin.mjs', import.meta.url), 'utf8');

test('authenticated shell navigation names real product surfaces and remains role-aware', () => {
  for (const target of ['section-chat', 'section-cora', 'section-cora-sessions', 'section-prepare', 'section-artifact', 'section-governance']) assert.match(page, new RegExp(`data-target="${target}"`, 'u'));
  assert.match(page, /data-admin-only/iu);
  assert.match(script, /adminNav\.hidden\s*=\s*!isAdmin/u);
  assert.match(page, /Search stored approved sources/iu);
  assert.match(page, /Organization scope/u);
  assert.doesNotMatch(page, /READ-ONLY PREVIEW/u);
});

test('shell does not present Plant/facility authority or fabricated execution', () => {
  assert.doesNotMatch(page, /plant selector|facility selector|choose a plant|choose a facility/iu);
  assert.match(page, /No audited status/u);
  assert.match(page, /no agent execution is implied/u);
  assert.match(page, /Preview · not executed/u);
  assert.match(page, /external execution and browser automation are unavailable/u);
  assert.match(page, /stored excerpts with citations only/u);
  assert.match(page, /Artifact Studio/u);
  assert.match(page, /Manual script and narration draft/u);
  assert.match(page, /Execution request preflight/u);
  assert.match(page, /Organization approvals inbox/u);
  assert.match(page, /Connector administration/u);
  assert.match(page, /Signing-secret reference name only/u);
  assert.match(page, /does not create a webhook/u);
  assert.match(script, /decideApproval/u);
  assert.match(script, /saveConnector/u);
  assert.match(liveAdmin, /LIVE_ADMIN_CORA_APPROVALS_PATH/u);
  assert.match(page, /approval-required, blocked, and queued states all remain not executed/iu);
  assert.match(page, /Your Cora preferences/iu);
  assert.match(page, /Open Cora quick controls/iu);
  assert.match(page, /Approved voice profile/iu);
  assert.match(page, /no provider or voice connection is claimed/iu);
  assert.match(page, /Organization policy, approved catalogs, provider keys, and voice readiness remain admin\/server controlled/iu);
  assert.match(script, /readPersonalPreferences/u);
  assert.match(script, /savePersonalPreferences/u);
  assert.match(page, /Workspace settings/iu);
  assert.match(page, /Reset to role default/iu);
  assert.match(script, /readWorkspaceLayout/u);
  assert.match(script, /saveWorkspaceLayout/u);
  assert.match(script, /resetWorkspaceLayout/u);
  assert.match(page, /Organization role defaults/iu);
  assert.match(page, /Save role default/iu);
  assert.match(script, /readWorkspaceRoleDefaults/u);
  assert.match(script, /saveWorkspaceRoleDefault/u);
  assert.match(script, /applyWorkspaceLayout/u);
  assert.match(script, /data-target=.{0,20}section-\$\{shelf\}/u);
  assert.match(page, /Routing policy is Organization-published metadata only/iu);
  assert.doesNotMatch(page, /Cora routing policy JSON/iu);
  assert.match(page, /Allowed member response detail/iu);
  assert.match(page, /Approved knowledge packs/iu);
  assert.match(page, /Save budget policy/iu);
  assert.match(page, /not provider invoice reconciliation/iu);
  assert.match(script, /saveUsagePolicy/u);
  assert.match(script, /allocationKey/u);
  assert.match(page, /Curated knowledge management/iu);
  assert.match(page, /Add draft source/iu);
  assert.match(page, /Bounded stored excerpt/iu);
  assert.match(script, /readKnowledgeAdmin/u);
  assert.match(script, /transitionKnowledge/u);
  assert.match(script, /routingPolicy/u);
  assert.match(script, /No generation occurred/u);
  assert.match(liveAdmin, /LIVE_ADMIN_CORA_ARTIFACT_EXECUTION_PATH = '\/api\/admin\/cora\/artifact-execution-requests'/u);
  assert.match(liveAdmin, /artifactExecution\.append\(actor, body\)/u);
  assert.match(page, /approved, queued, running, provider result, accepted, and rejected execution stages are not performed/u);
  assert.match(page, /Cora Sessions/u);
  assert.match(script, /readCoraSessions/u);
  assert.match(page, /No provider evidence recorded|Unknown usage/u);
  assert.match(page, /No session close or mutation is available/iu);
  assert.match(page, /Hume session preflight/iu);
  assert.match(page, /does not mean Hume is connected or accepted/iu);
  assert.match(script, /readCoraHumePreflight/u);
  assert.match(liveAdmin, /LIVE_ADMIN_CORA_HUME_PREFLIGHT_PATH/u);
});
