import assert from 'node:assert/strict';
import test from 'node:test';
import { normalizeAppBuildApproval, normalizeAppBuildRevision } from '../src/cora/app-build-revision.mjs';
import { createAppBuildRevisionRepository } from '../src/cora/app-build-revision-repository.mjs';

const draft = { appBuildReceiptId: 'app-draft-0001', description: 'Review onboarding fields.', components: [{ type: 'heading', text: 'Onboarding' }], reason: 'Initial safe revision', idempotencyKey: 'app-revision-0001' };
function pool() { const revisions=[]; const approvals=[]; const members={member:{tenant_id:'org-a',role:'member'},admin:{tenant_id:'org-a',role:'admin'},other:{tenant_id:'org-b',role:'admin'}}; const client={async query(sql,v=[]){const q=String(sql).replace(/\s+/g,' ').toLowerCase(); if(['begin','commit','rollback'].includes(q.trim())||q.startsWith('select set_config'))return{rowCount:0,rows:[]}; if(q.startsWith('select role from helmion.tenant_memberships')){const m=members[v[1]];return m?.tenant_id===v[0]?{rowCount:1,rows:[{role:m.role}]}:{rowCount:0,rows:[]};} if(q.includes('from helmion.cora_app_build_requests'))return v[0]==='org-a'&&v[1]==='app-draft-0001'?{rowCount:1,rows:[{id:1,receipt_id:'app-draft-0001'}]}:{rowCount:0,rows:[]}; if(q.startsWith('select coalesce(max(revision)'))return{rowCount:1,rows:[{next_revision:revisions.length+1}]}; if(q.startsWith('insert into helmion.cora_app_build_revisions')){const ex=revisions.find(x=>x.idempotency_key===v[8]);if(ex)return{rowCount:0,rows:[]};const r={id:revisions.length+1,app_build_receipt_id:v[2],revision:v[3],description:v[4],components:JSON.parse(v[5]),reason:v[6],receipt_id:v[7],idempotency_key:v[8]};revisions.push(r);return{rowCount:1,rows:[r]};} if(q.includes('from helmion.cora_app_build_revisions where tenant_id=$1 and idempotency_key')){const r=revisions.find(x=>x.idempotency_key===v[1]);return r?{rowCount:1,rows:[r]}:{rowCount:0,rows:[]};} if(q.includes('from helmion.cora_app_build_revisions where tenant_id=$1 and receipt_id')){const r=revisions.find(x=>x.receipt_id===v[1]);return r?{rowCount:1,rows:[r]}:{rowCount:0,rows:[]};} if(q.startsWith('insert into helmion.cora_app_build_approval_decisions')){const ex=approvals.find(x=>x.idempotency_key===v[6]);if(ex)return{rowCount:0,rows:[]};const a={revision_receipt_id:v[2],decision:v[3],reason:v[4],receipt_id:v[5],idempotency_key:v[6]};approvals.push(a);return{rowCount:1,rows:[a]};} if(q.includes('from helmion.cora_app_build_approval_decisions where tenant_id=$1 and idempotency_key')){const a=approvals.find(x=>x.idempotency_key===v[1]);return a?{rowCount:1,rows:[a]}:{rowCount:0,rows:[]};} throw new Error(`Unexpected ${q}`)},release(){}};return{connect:async()=>client};}
const member={tenantId:'org-a',subject:'member',role:'member',sessionId:'s',requestId:'r'}; const admin={...member,subject:'admin',role:'admin'};
test('revision normalizer rejects authority injection and unsafe component types',()=>{assert.throws(()=>normalizeAppBuildRevision({...draft,tenantId:'org-b'}),/cannot select tenant/);assert.throws(()=>normalizeAppBuildRevision({...draft,components:[{type:'html'}]}),/invalid/);assert.throws(()=>normalizeAppBuildApproval({revisionReceiptId:'rev-1',decision:'publish',reason:'x',idempotencyKey:'approval-0001'}),/invalid/);});
test('tenant member records immutable idempotent revision; only owner/admin decides future publish',async()=>{const repo=createAppBuildRevisionRepository(pool());const first=await repo.appendRevision(member,draft);const replay=await repo.appendRevision(member,draft);assert.equal(first.durable,true);assert.equal(first.execution,'not_performed');assert.equal(first.publication,'not_performed');assert.equal(replay.replayed,true);await assert.rejects(()=>repo.appendRevision({...member,tenantId:'org-b',subject:'other',role:'admin'},draft),/unavailable/);await assert.rejects(()=>repo.decideApproval(member,{revisionReceiptId:first.receiptId,decision:'approve',reason:'reviewed',idempotencyKey:'approval-0001'}),/owner or admin/);const approval=await repo.decideApproval(admin,{revisionReceiptId:first.receiptId,decision:'approve',reason:'reviewed',idempotencyKey:'approval-0001'});assert.equal(approval.durable,true);assert.equal(approval.publication,'not_performed');const approvalReplay=await repo.decideApproval(admin,{revisionReceiptId:first.receiptId,decision:'approve',reason:'reviewed',idempotencyKey:'approval-0001'});assert.equal(approvalReplay.replayed,true);});
