import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, rm, symlink, mkdir, writeFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { createApprovedAppBuildWorkerPlan } from '../src/cora/app-build-worker-plan.mjs';
import { executeApprovedAppBuildPlan } from '../src/cora/app-build-local-executor.mjs';

const input = { tenantId: 'org-a', revision: { receiptId: 'revision-0001', appBuildReceiptId: 'draft-0001', route: '/hr/onboarding', title: 'Driver onboarding', description: 'Collect onboarding details.', components: [{ type: 'heading', text: 'Driver onboarding' }] }, approval: { revisionReceiptId: 'revision-0001', decision: 'approve', actorRole: 'admin', receiptId: 'approval-0001' }, workspaceProject: { projectKey: 'tms-cloud', sourceKind: 'git', defaultBranch: 'main' } };
async function workspace(t) { const root = await mkdtemp(join(tmpdir(), 'cora-app-build-')); t.after(() => rm(root, { recursive: true, force: true })); return root; }
test('executor writes only declared deterministic artifacts and returns hashes plus rollback receipt', async (t) => { const root = await workspace(t); const plan = createApprovedAppBuildWorkerPlan(input); const receipt = await executeApprovedAppBuildPlan({ workspaceRoot: root, plan }); assert.equal(receipt.written.length, 2); assert.equal(receipt.verification.status, 'passed'); assert.equal(receipt.rollback.path, 'generated-apps/hr-onboarding'); assert.match(await readFile(join(root, 'generated-apps/hr-onboarding/definition.json'), 'utf8'), /Driver onboarding/); assert.equal(receipt.providerInvocation, 'not_performed'); });
test('executor rejects tampered digests and path escapes before write', async (t) => { const root = await workspace(t); const plan = createApprovedAppBuildWorkerPlan(input); await assert.rejects(() => executeApprovedAppBuildPlan({ workspaceRoot: root, plan: { ...plan, changes: [{ ...plan.changes[0], contentDigest: 'bad' }, plan.changes[1]] } }), /digest/); await assert.rejects(() => executeApprovedAppBuildPlan({ workspaceRoot: root, plan: { ...plan, changes: [{ ...plan.changes[0], path: '../escape' }, plan.changes[1]], artifacts: [{ ...plan.artifacts[0], path: '../escape' }, plan.artifacts[1]] } }), /path/); });
test('executor rejects a symlinked generated-apps ancestor', async (t) => { const root = await workspace(t); const outside = await mkdtemp(join(tmpdir(), 'cora-outside-')); t.after(() => rm(outside, { recursive: true, force: true })); try { await symlink(outside, join(root, 'generated-apps'), 'junction'); } catch (error) { t.skip(`symlink unavailable: ${error.code}`); return; } await assert.rejects(() => executeApprovedAppBuildPlan({ workspaceRoot: root, plan: createApprovedAppBuildWorkerPlan(input) }), /symlink/); });
test('pre-existing second artifact refuses before write and leaves no newly-created first artifact', async (t) => { const root = await workspace(t); const plan = createApprovedAppBuildWorkerPlan(input); const second = join(root, plan.changes[1].path); await mkdir(join(root, 'generated-apps/hr-onboarding'), { recursive: true }); await writeFile(second, 'user file', 'utf8'); await assert.rejects(() => executeApprovedAppBuildPlan({ workspaceRoot: root, plan }), /already exists/); await assert.rejects(() => stat(join(root, plan.changes[0].path)), /ENOENT/); assert.equal(await readFile(second, 'utf8'), 'user file'); });
test('forged matching-digest malformed JSON or script is rejected before any write', async (t) => { const root = await workspace(t); const base = createApprovedAppBuildWorkerPlan(input); const hash = (text) => createHash('sha256').update(text).digest('hex'); for (const [index, text, error] of [[0, '{bad', /invalid JSON/], [1, 'process.exit(1);\n', /deterministic safe contract/]]) { const artifacts = base.artifacts.map((item, current) => current === index ? { ...item, text } : item); const changes = base.changes.map((item, current) => current === index ? { ...item, contentDigest: hash(text) } : item); await assert.rejects(() => executeApprovedAppBuildPlan({ workspaceRoot: root, plan: { ...base, artifacts, changes } }), error); await assert.rejects(() => stat(join(root, base.changes[0].path)), /ENOENT/); await assert.rejects(() => stat(join(root, base.changes[1].path)), /ENOENT/); } });
