import assert from 'node:assert/strict';
import test from 'node:test';
import { createGuardedNeonSnapshot } from '../src/adapters/neon-snapshot-preflight.mjs';

function response(body, status = 200) { return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } }); }
function fixture(overrides = {}) { const calls = []; const fetchImpl = async (url, init = {}) => { calls.push({ url: String(url), init }); const path = new URL(url).pathname; if (path === '/api/v2/projects') return response({ projects: [{ id: 'project-1' }] }); if (path.endsWith('/endpoints')) return response({ endpoints: [{ id: 'ep-proud-truth-a69e8vg4', branch_id: 'br-root' }] }); if (path.endsWith('/branches')) return response({ branches: [{ id: 'br-root', parent_id: null }] }); if (path.endsWith('/snapshots')) return response({ snapshots: [{ id: 'snap-1', name: 'before-cora', created_at: '2026-08-16T00:00:00Z' }] }); if (path.includes('/snapshot')) return response({ snapshot: { id: 'snap-1', name: 'before-cora' }, operations: [{ id: 'op-1' }] }); if (path.includes('/operations/')) return response({ operation: { id: 'op-1', status: 'finished' } }); throw new Error(path); }; return { calls, fetchImpl: overrides.fetchImpl ?? fetchImpl }; }
test('guarded snapshot locates endpoint, requires root branch, polls, and reads back receipt', async () => { const f = fixture(); const apiKey = 'test-api-key-not-for-output'; const receipt = await createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'before-cora', apiKey, fetchImpl: f.fetchImpl, sleep: async () => {} }); assert.deepEqual(receipt, { projectId: 'project-1', branchId: 'br-root', endpointId: 'ep-proud-truth-a69e8vg4', snapshot: { id: 'snap-1', name: 'before-cora', createdAt: '2026-08-16T00:00:00Z' }, operation: { id: 'op-1', status: 'finished' } }); assert.equal(f.calls.some((call) => call.init.headers.authorization === `Bearer ${apiKey}`), true); const serialized = JSON.stringify(receipt); assert.equal(serialized.includes(apiKey), false); assert.equal(serialized.includes('postgresql://'), false); });
test('snapshot preflight refuses absent key before fetch, endpoint misses/multiples, non-root, malformed/non-2xx, and timeout', async () => { let calls = 0; await assert.rejects(createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'x', fetchImpl: async () => { calls += 1; } }), /NEON_API_KEY/); assert.equal(calls, 0); const cases = [
  async () => createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'x', apiKey: 'k', fetchImpl: async (url) => new URL(url).pathname.endsWith('/projects') ? response({ projects: [] }) : response({}) }),
  async () => createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'x', apiKey: 'k', fetchImpl: async () => response({}, 500) }),
  async () => createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'x', apiKey: 'k', fetchImpl: async (url) => new URL(url).pathname.endsWith('/projects') ? response({ projects: [{ id: 'p' }] }) : new URL(url).pathname.endsWith('/endpoints') ? response({ endpoints: [{ id: 'ep-proud-truth-a69e8vg4', branch_id: 'b' }] }) : response({ branches: [{ id: 'b', parent_id: 'parent' }] }) }),
  async () => createGuardedNeonSnapshot({ endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'x', apiKey: 'k', fetchImpl: async (url) => { const p = new URL(url).pathname; if (p.endsWith('/projects')) return response({ projects: [{ id: 'p' }] }); if (p.endsWith('/endpoints')) return response({ endpoints: [{ id: 'ep-proud-truth-a69e8vg4', branch_id: 'b' }] }); if (p.endsWith('/branches')) return response({ branches: [{ id: 'b', parent_id: null }] }); if (p.includes('/snapshot')) return response({ snapshot: { id: 's' }, operations: [{ id: 'o' }] }); if (p.includes('/operations/')) return response({ operation: { status: 'running' } }); return response({}); }, pollLimit: 1 }),
]; for (const run of cases) await assert.rejects(run()); });

test('snapshot preflight refuses an endpoint collision before branch or snapshot requests', async () => {
  const paths = [];
  await assert.rejects(createGuardedNeonSnapshot({
    endpointId: 'ep-proud-truth-a69e8vg4', snapshotName: 'before-cora', apiKey: 'test-key',
    fetchImpl: async (url) => { const path = new URL(url).pathname; paths.push(path); if (path === '/api/v2/projects') return response({ projects: [{ id: 'project-a' }, { id: 'project-b' }] }); if (path.endsWith('/endpoints')) return response({ endpoints: [{ id: 'ep-proud-truth-a69e8vg4', branch_id: 'br-root' }] }); throw new Error(`must not request ${path}`); },
  }), /matched multiple Neon projects/u);
  assert.deepEqual(paths, ['/api/v2/projects', '/api/v2/projects/project-a/endpoints', '/api/v2/projects/project-b/endpoints']);
});
