<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helmion.Desktop.Core\Helmion.Desktop.Core.csproj" />
    <ProjectReference Include="..\Helmion.LocalService.Protocol\Helmion.LocalService.Protocol.csproj" />
    <ProjectReference Include="..\Helmion.LocalService.Security\Helmion.LocalService.Security.csproj" />
    <ProjectReference Include="..\Helmion.LocalService\Helmion.LocalService.csproj" />
  </ItemGroup>
</Project>
