const status = document.querySelector('#connector-status');
const items = document.querySelector('#connector-items');
const form = document.querySelector('#connector-form');
const provider = document.querySelector('#connector-provider');
const lifecycle = document.querySelector('#connector-lifecycle');
const secretReferenceName = document.querySelector('#connector-secret-ref');
const endpointReady = document.querySelector('#connector-endpoint-ready');
const channels = document.querySelector('#connector-channels');
const save = document.querySelector('#connector-save');
let isAdmin = false;

function card(registration, verifierStatus = {}) { const article = document.createElement('article'); const heading = document.createElement('h2'); heading.textContent = `${registration.provider || 'Connector'} · ${registration.lifecycle || 'unavailable'}`; const readiness = document.createElement('p'); readiness.textContent = `Registration metadata: ${registration.enabled ? 'enabled' : 'not enabled'}; endpoint readiness: ${registration.publicEndpointReady ? 'declared' : 'not declared'}; last verifier status: ${registration.lastVerifiedStatus || 'not verified'}.`; const live = document.createElement('p'); const runtime = verifierStatus[registration.provider] || {}; live.textContent = runtime.configured === true ? 'Runtime configuration is declared by the server, but this page does not claim OAuth, provider authorization, repository access, or delivery.' : 'No live connection is established. OAuth/provider authorization, repository access, and delivery are not performed.'; article.append(heading, readiness, live); return article; }
function render(body) { items.replaceChildren(); const registrations = Array.isArray(body.registrations) ? body.registrations : []; if (registrations.length === 0) { const empty = document.createElement('p'); empty.textContent = 'No connector registration metadata exists for this Organization.'; items.append(empty); } for (const registration of registrations) items.append(card(registration, body.verifierStatus)); status.textContent = registrations.length ? `${registrations.length} connector registration receipt(s) loaded. None implies a connected OAuth/provider.` : 'No connector registrations recorded. No live connection is implied.'; }
async function load() { status.textContent = 'Loading connector registration metadata…'; try { const session = await fetch('/api/admin/session', { credentials: 'same-origin' }); const sessionBody = await session.json(); if (!session.ok) throw Object.assign(new Error(sessionBody.code || 'Session unavailable'), { status: session.status }); isAdmin = ['owner', 'admin'].includes(String(sessionBody.actor?.role || '').toLowerCase()); form.hidden = !isAdmin; const response = await fetch('/api/admin/cora/connectors', { credentials: 'same-origin' }); const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.code || 'Connector registrations unavailable'), { status: response.status }); render(body); } catch (error) { items.replaceChildren(); form.hidden = true; status.textContent = error.status === 403 ? 'Connector status unavailable: active Organization membership is required.' : `Connector status unavailable: ${error.message}`; } }
form.addEventListener('submit', async (event) => { event.preventDefault(); if (!isAdmin) return; save.disabled = true; status.textContent = 'Saving connector registration metadata…'; try { const allowedInboundChannels = channels.value.split('\n').map((line) => line.split('|').map((part) => part.trim())).filter((parts) => parts.length >= 2 && parts[0] && parts[1]).map(([externalChannelId, label]) => ({ externalChannelId, label, enabled: true })); const response = await fetch('/api/admin/cora/connectors', { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ provider: provider.value, lifecycle: lifecycle.value, enabled: lifecycle.value === 'enabled', publicEndpointReady: endpointReady.checked, secretReferenceName: secretReferenceName.value.trim() || null, allowedInboundChannels }) }); const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.code || 'Connector registration was not saved'), { status: response.status }); status.textContent = 'Connector registration metadata saved. OAuth, provider authorization, repository access, delivery, and execution remain not performed.'; form.reset(); await load(); } catch (error) { status.textContent = error.status === 403 ? 'Connector registration not saved: owner/admin membership is required.' : `Connector registration not saved: ${error.message}`; } finally { save.disabled = false; } });
void load();
