const endpoints = Object.freeze({ session: '/api/admin/session', drafts: '/api/admin/cora/app-builds', prompt: '/api/admin/cora/app-builds/from-prompt', revisions: '/api/admin/cora/app-build-revisions', approvals: '/api/admin/cora/app-build-approvals', queue: '/api/admin/cora/app-build-execution-requests', projects: '/api/admin/workspace/projects', bindings: '/api/admin/workspace/github-app-source-bindings' });
const byId = (id) => document.querySelector(`#${id}`);
const status = byId('status'); const drafts = byId('drafts'); const revisions = byId('revisions'); const bindings = byId('bindings'); const receipt = byId('receipt');
const promptForm = byId('prompt-form'); const revisionForm = byId('revision-form'); const approvalForm = byId('approval-form'); const queueForm = byId('queue-form');
const prompt = byId('user-request'); const revisionDraft = byId('revision-draft'); const revisionTitle = byId('revision-title'); const revisionDescription = byId('revision-description'); const revisionReason = byId('revision-reason'); const approvalRevision = byId('approval-revision'); const approvalDecision = byId('approval-decision'); const approvalReason = byId('approval-reason'); const queueRevision = byId('queue-revision'); const queueApproval = byId('queue-approval'); const queueProject = byId('queue-project');
let isAdmin = false;

async function requestJson(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', ...options }); const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.code || 'Request failed'), { status: response.status }); return body; }
function item(label, value) { const p = document.createElement('p'); p.textContent = `${label}: ${value || 'unavailable'}`; return p; }
function card(title, fields) { const article = document.createElement('article'); const heading = document.createElement('h3'); heading.textContent = title; article.append(heading, ...fields.map(([label, value]) => item(label, value))); return article; }
function replaceOptions(select, placeholder, entries) { const previous = select.value; select.replaceChildren(new Option(placeholder, '')); for (const entry of entries) select.add(new Option(entry.label, entry.value)); select.value = [...select.options].some((option) => option.value === previous) ? previous : ''; }
function renderDrafts(body) { const entries = Array.isArray(body.receipts) ? body.receipts : []; drafts.replaceChildren(); replaceOptions(revisionDraft, 'Select a draft', entries.map((entry) => ({ value: entry.receiptId, label: `${entry.title || 'Untitled'} · ${entry.receiptId}` }))); if (!entries.length) { drafts.append(item('Drafts', 'No draft receipts recorded for this tenant.')); return; } for (const entry of entries) drafts.append(card('Draft receipt', [['Title / route', `${entry.title || 'Untitled'} · ${entry.route || 'route unavailable'}`], ['Receipt', entry.receiptId], ['Execution / files / publish / deploy', 'Not performed']])); }
function renderRevisions(body) { const entries = Array.isArray(body.receipts) ? body.receipts : []; revisions.replaceChildren(); const options = entries.map((entry) => ({ value: entry.receiptId, label: `Revision ${entry.revision || 'unavailable'} · ${entry.receiptId}` })); replaceOptions(approvalRevision, 'Select a revision', options); replaceOptions(queueRevision, 'Select a revision', options); if (!entries.length) { revisions.append(item('Revisions', 'Select a draft to view its revision receipts.')); return; } for (const entry of entries) revisions.append(card('Revision receipt', [['Revision / receipt', `${entry.revision || 'unavailable'} · ${entry.receiptId}`], ['Reason', entry.reason], ['Execution / files / publish / deploy', 'Not performed']])); }
async function loadRevisions() { if (!revisionDraft.value) { renderRevisions({ receipts: [] }); return; } try { renderRevisions(await requestJson(`${endpoints.revisions}?app_build_receipt_id=${encodeURIComponent(revisionDraft.value)}`)); } catch (error) { revisions.replaceChildren(item('Revisions unavailable', error.status === 403 ? 'Active tenant membership is required.' : error.message)); } }
function renderProjects(body) { const projects = Array.isArray(body.projects) ? body.projects : []; replaceOptions(queueProject, 'Select an active workspace project', projects.filter((project) => project.lifecycle === 'active').map((project) => ({ value: project.projectKey, label: `${project.displayName} · ${project.projectKey}` }))); }
function renderBindings(body) { bindings.replaceChildren(); const entries = Array.isArray(body.receipts) ? body.receipts : []; if (!entries.length) { bindings.append(item('GitHub source binding', 'No binding receipt recorded. Queueing cannot execute.')); return; } for (const entry of entries) bindings.append(card('GitHub source-binding receipt', [['Workspace project', entry.workspaceProjectKey], ['Lifecycle', entry.lifecycle || 'pending_verification'], ['Verification', 'Not performed by this studio; no checkout or source verification occurred.']])); }
async function loadAdminSupport() { try { const [projectsBody, bindingsBody] = await Promise.all([requestJson(endpoints.projects), requestJson(endpoints.bindings)]); renderProjects(projectsBody); renderBindings(bindingsBody); } catch (error) { bindings.replaceChildren(item('Workspace/source status unavailable', error.status === 403 ? 'Owner/admin membership is required.' : error.message)); } }
async function loadDrafts() { try { renderDrafts(await requestJson(endpoints.drafts)); } catch (error) { drafts.replaceChildren(item('Drafts unavailable', error.status === 403 ? 'Active tenant membership is required.' : error.message)); } }
function idempotencyKey() { return crypto.randomUUID(); }
function setControlsVisible(visible) { for (const form of [promptForm, revisionForm, approvalForm, queueForm]) form.hidden = !visible; }
async function load() { status.textContent = 'Checking session…'; try { const session = await requestJson(endpoints.session); isAdmin = ['owner', 'admin'].includes(String(session.actor?.role || '').toLowerCase()); setControlsVisible(isAdmin); status.textContent = isAdmin ? 'Owner/admin controls available. Every action records a receipt; queueing does not execute.' : 'Read-only: owner/admin membership is required to create drafts, revisions, approvals, or queue requests.'; await loadDrafts(); if (isAdmin) await loadAdminSupport(); } catch (error) { setControlsVisible(false); status.textContent = error.status === 403 ? 'Build Studio unavailable: active tenant membership is required.' : `Build Studio unavailable: ${error.message}`; } }

revisionDraft.addEventListener('change', () => { void loadRevisions(); });
promptForm.addEventListener('submit', async (event) => { event.preventDefault(); const userRequest = prompt.value.trim(); if (!isAdmin || !userRequest) return; const button = byId('prompt-submit'); button.disabled = true; try { const result = await requestJson(endpoints.prompt, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ userRequest }) }); prompt.value = ''; status.textContent = `Draft receipt ${result.receiptId || 'recorded'} created. It is not approved, executed, written to files, published, or deployed.`; await loadDrafts(); } catch (error) { status.textContent = error.status === 403 ? 'Draft not recorded: owner/admin membership is required.' : error.status === 503 ? 'Planner unavailable: no draft was recorded.' : `Draft not recorded: ${error.message}`; } finally { button.disabled = false; } });
revisionForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!isAdmin || !revisionDraft.value || !revisionTitle.value.trim() || !revisionDescription.value.trim() || !revisionReason.value.trim()) return; const button = byId('revision-submit'); button.disabled = true; try { await requestJson(endpoints.revisions, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ appBuildReceiptId: revisionDraft.value, components: [{ type: 'heading', text: revisionTitle.value.trim() }, { type: 'field', label: 'Contact email', fieldType: 'email', required: true }, { type: 'button', label: 'Save draft', action: 'save_draft' }], description: revisionDescription.value.trim(), reason: revisionReason.value.trim(), idempotencyKey: idempotencyKey() }) }); revisionTitle.value = ''; revisionDescription.value = ''; revisionReason.value = ''; status.textContent = 'Revision receipt recorded. No files, publish, or deploy occurred.'; await loadRevisions(); } catch (error) { status.textContent = error.status === 403 ? 'Revision not recorded: owner/admin membership is required.' : `Revision not recorded: ${error.message}`; } finally { button.disabled = false; } });
approvalForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!isAdmin || !approvalRevision.value || !approvalReason.value.trim()) return; const button = byId('approval-submit'); button.disabled = true; try { const result = await requestJson(endpoints.approvals, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ revisionReceiptId: approvalRevision.value, decision: approvalDecision.value, reason: approvalReason.value.trim(), idempotencyKey: idempotencyKey() }) }); approvalReason.value = ''; if (result.decision === 'approve') { queueRevision.value = approvalRevision.value; queueApproval.value = result.receiptId || ''; } status.textContent = `${result.decision === 'approve' ? 'Approval' : 'Rejection'} receipt recorded. No files, publish, or deploy occurred.`; } catch (error) { status.textContent = error.status === 403 ? 'Decision not recorded: owner/admin membership is required.' : `Decision not recorded: ${error.message}`; } finally { button.disabled = false; } });
queueForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!isAdmin || !queueRevision.value || !queueApproval.value.trim() || !queueProject.value) return; const button = byId('queue-submit'); button.disabled = true; try { const result = await requestJson(endpoints.queue, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ revisionReceiptId: queueRevision.value, approvalReceiptId: queueApproval.value.trim(), workspaceProjectKey: queueProject.value, idempotencyKey: idempotencyKey() }) }); receipt.replaceChildren(card('Queued execution request receipt', [['Receipt', result.receiptId], ['Status', result.status || 'queued'], ['Execution / files / source verification / checkout / publish / deploy', 'Not performed']])); queueApproval.value = ''; status.textContent = 'Queued request recorded only. It does not execute until a verified GitHub source binding and real worker runtime exist.'; } catch (error) { status.textContent = error.status === 403 ? 'Queue request not recorded: owner/admin membership is required.' : `Queue request not recorded: ${error.message}`; } finally { button.disabled = false; } });
void load();
