const search = document.querySelector('#project-search');
const active = document.querySelector('#active-filter');
const archived = document.querySelector('#archived-filter');
const clear = document.querySelector('#project-clear');
const list = document.querySelector('#project-list');
const status = document.querySelector('#workspace-status');
const count = document.querySelector('#project-count');
const registration = document.querySelector('#registration');
let projects = []; let lifecycle = 'active';

function visibleProjects() { const needle = search.value.trim().toLowerCase(); return projects.filter((project) => project.lifecycle === lifecycle && (!needle || `${project.displayName} ${project.projectKey}`.toLowerCase().includes(needle))); }
function selectProject(project, card) { for (const item of list.querySelectorAll('article')) item.classList.remove('selected'); card.classList.add('selected'); status.textContent = `${project.displayName} is selected. This Cloud shelf does not open a local folder or execute project work.`; }
function projectCard(project) { const card = document.createElement('article'); const button = document.createElement('button'); button.type = 'button'; button.className = 'project-row'; const head = document.createElement('div'); head.className = 'project-head'; const title = document.createElement('h2'); title.textContent = project.displayName; const tag = document.createElement('span'); tag.className = 'tag'; tag.textContent = project.lifecycle.toUpperCase(); head.append(title, tag); const meta = document.createElement('p'); meta.className = 'meta'; meta.textContent = `${project.projectKey} · ${project.sourceKind.replace('_', ' ')} · ${project.defaultBranch}`; button.append(head, meta); button.addEventListener('click', () => selectProject(project, card)); card.append(button); return card; }
function render() { const shown = visibleProjects(); list.replaceChildren(); if (!shown.length) { const empty = document.createElement('p'); empty.textContent = search.value.trim() ? `No ${lifecycle} project matches "${search.value.trim()}".` : `No ${lifecycle} projects are registered for this Organization.`; list.append(empty); } for (const project of shown) list.append(projectCard(project)); count.textContent = `${shown.length} ${lifecycle.toUpperCase()} PROJECT${shown.length === 1 ? '' : 'S'}`; }
function setLifecycle(next) { lifecycle = next; active.setAttribute('aria-pressed', String(next === 'active')); archived.setAttribute('aria-pressed', String(next === 'archived')); render(); }
async function load() { status.textContent = 'Loading Organization projects…'; try { const response = await fetch('/api/admin/workspace/projects', { credentials:'same-origin' }); const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.code || 'Workspace projects unavailable'), { status:response.status }); projects = Array.isArray(body.projects) ? body.projects : []; registration.hidden = !body.canManage; status.textContent = projects.length ? 'Choose a project to inspect its Cloud registry record.' : 'No Cloud project records are registered yet.'; render(); } catch (error) { projects = []; registration.hidden = true; render(); status.textContent = error.status === 403 ? 'Workspace projects unavailable: active Organization membership is required.' : `Workspace projects unavailable: ${error.message}`; } }
search.addEventListener('input', render); active.addEventListener('click', () => setLifecycle('active')); archived.addEventListener('click', () => setLifecycle('archived')); clear.addEventListener('click', () => { search.value = ''; setLifecycle('active'); });
registration.addEventListener('submit', async (event) => { event.preventDefault(); const save = document.querySelector('#project-save'); save.disabled = true; status.textContent = 'Registering the Cloud project record…'; try { const response = await fetch('/api/admin/workspace/projects', { method:'POST', credentials:'same-origin', headers:{'content-type':'application/json'}, body:JSON.stringify({ projectKey:document.querySelector('#project-key').value.trim(), displayName:document.querySelector('#project-name').value.trim(), sourceKind:document.querySelector('#project-source').value, defaultBranch:document.querySelector('#project-branch').value.trim(), lifecycle:'active' }) }); const body = await response.json(); if (!response.ok) throw new Error(body.code || 'Project registration unavailable'); status.textContent = `Registered ${body.project.displayName}. The durable receipt is recorded by the tenant project registry; no project execution was performed.`; registration.reset(); document.querySelector('#project-branch').value = 'main'; await load(); } catch (error) { status.textContent = `Project registration unavailable: ${error.message}`; } finally { save.disabled = false; } });
void load();
