-- Immutable revisions and approval receipts for declarative app-build drafts.
-- This migration does not generate code, invoke a provider/worker, mutate a workspace, publish, or deploy.
create table if not exists helmion.cora_app_build_revisions (
 id bigserial primary key, tenant_id text not null references helmion.tenants(tenant_id) on delete cascade,
 app_build_request_id bigint not null references helmion.cora_app_build_requests(id) on delete restrict,
 app_build_receipt_id text not null, revision integer not null check (revision > 0), description text not null check(char_length(description) between 1 and 1200), components jsonb not null check(jsonb_typeof(components)='array' and jsonb_array_length(components) between 1 and 32), reason text not null check(char_length(reason) between 1 and 600), receipt_id text not null check(char_length(receipt_id) between 8 and 256), idempotency_key text not null check(idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'), created_by_subject text not null check(char_length(created_by_subject) between 1 and 256), execution text not null default 'not_performed' check(execution='not_performed'), provider_invocation text not null default 'not_performed' check(provider_invocation='not_performed'), agent_invocation text not null default 'not_performed' check(agent_invocation='not_performed'), filesystem_mutation text not null default 'not_performed' check(filesystem_mutation='not_performed'), publication text not null default 'not_performed' check(publication='not_performed'), created_at timestamptz not null default clock_timestamp(), unique(tenant_id,app_build_request_id,revision), unique(tenant_id,receipt_id), unique(tenant_id,idempotency_key));
create table if not exists helmion.cora_app_build_approval_decisions (
 id bigserial primary key, tenant_id text not null references helmion.tenants(tenant_id) on delete cascade, revision_id bigint not null references helmion.cora_app_build_revisions(id) on delete restrict, revision_receipt_id text not null, decision text not null check(decision in ('approve','reject')), reason text not null check(char_length(reason) between 1 and 600), receipt_id text not null check(char_length(receipt_id) between 8 and 256), idempotency_key text not null check(idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'), actor_subject text not null check(char_length(actor_subject) between 1 and 256), actor_role text not null check(actor_role in ('owner','admin')), execution text not null default 'not_performed' check(execution='not_performed'), provider_invocation text not null default 'not_performed' check(provider_invocation='not_performed'), agent_invocation text not null default 'not_performed' check(agent_invocation='not_performed'), filesystem_mutation text not null default 'not_performed' check(filesystem_mutation='not_performed'), publication text not null default 'not_performed' check(publication='not_performed'), created_at timestamptz not null default clock_timestamp(), unique(tenant_id,revision_id), unique(tenant_id,receipt_id), unique(tenant_id,idempotency_key));
create or replace function helmion.reject_cora_app_build_revision_mutation() returns trigger language plpgsql as $$ begin raise exception 'cora app build revision receipts are append-only'; end; $$;
create trigger cora_app_build_revision_append_only before update or delete on helmion.cora_app_build_revisions for each row execute function helmion.reject_cora_app_build_revision_mutation();
create trigger cora_app_build_approval_append_only before update or delete on helmion.cora_app_build_approval_decisions for each row execute function helmion.reject_cora_app_build_revision_mutation();
alter table helmion.cora_app_build_revisions enable row level security; alter table helmion.cora_app_build_approval_decisions enable row level security;
create policy cora_app_build_revisions_select on helmion.cora_app_build_revisions for select using(tenant_id=current_setting('helmion.tenant_id',true)); create policy cora_app_build_revisions_insert on helmion.cora_app_build_revisions for insert with check(tenant_id=current_setting('helmion.tenant_id',true));
create policy cora_app_build_approvals_select on helmion.cora_app_build_approval_decisions for select using(tenant_id=current_setting('helmion.tenant_id',true)); create policy cora_app_build_approvals_insert on helmion.cora_app_build_approval_decisions for insert with check(tenant_id=current_setting('helmion.tenant_id',true));
